### ISSUE TITLE
Attempt to make --help visibible outside of mpi just breaks the help

### ISSUE THREAD

**Issue by Micket** [VI4IO/pfind#17]
trying to use `--help` right now is just broken, since the help parser tries to fetch the rank before initialization, so you end up with just:
```
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```

In addition, the supposed `-h` flag that the help mentions just doesn't exist.
```
mpirun -n 1 ./pfind -h
Pfind: cannot open directory '/dev/shm/pfind/20220604/gompi-2021b/pfind-d97bcb944f49941ba3b701bb20039da1aa296153/-h': No such file or directory
```

leaving no way at all to read the help.

**Comment by JulianKunkel** [comment]
Should work again:

$ ./pfind -h
pfind 
Synopsis:
pfind <workdir> [-newer <timestamp file>] [-size <size>c] [-name <substr>] [-regex <regex>]
	workdir = "./"
	-newer = "(null)"
	-name|-regex = "(null)"

Flags
  -E                            Erase empty directories
  -e                            Erase files matched
  -N                            steal with 50%% likelihood from the next process instead of randomly
  -P                            output per process for debugging and checks loadbalance
  -C                            don't output file names just count the number of files found
  -v                            increase the verbosity, use multiple times to increase level

Optional arguments
  -M=1000                       maximum number of elements to process per readdir iteration
  -s=0                          Stonewall timer for find
  -q=100000                     queue length (max pending ops)
  -D=STRING                     [rates]: print rates
  -H=0                          parallelize single directory access [option 1=hashing, option 2=sequential]
  -r=STRING                     Where to store results

**Comment by Micket** [comment]
Yes looks good.
