### ISSUE TITLE
Last pending directory waits in the queue instead of being handed off

### ISSUE THREAD

**Issue by sinelaw** [VI4IO/pfind#9]
Consider a base dir that has only two (very large) subdirectories. It queues up both large dirs, and then enters one of them leaving the queue with the other large dir waiting forever because it won't give it away.
The root cause appears to be this line:
```
int work_to_give = pending_work / 2;
```
Integer arithmetic means if pending_work = 1, then work_to_give = 0.
Possible fix - to change it to `(pending_work + 1) / 2`

**Comment by JulianKunkel** [comment]
Thx for submitting the bug report.
The issue was a bit more complex to fix properly, as the pending_work was decremented for open directories. Now even when starting to process a directory, the pending_work is not decremented, ensuring that pending_work is >= 1
Fix  is here: 6abf20fb2ac9cc36e90860cac29cce51d4f44f3e

**Comment by sinelaw** [comment]
Thanks for the quick response!
